### ISSUE TITLE
thumbfast integration request

### ISSUE THREAD

**Issue by odopo** [1-minute-to-midnight/mpv-modern-x-compact#1]
Can you please add thumbfast support to this OSC?

https://github.com/po5/thumbfast

**Comment by 1-minute-to-midnight** [comment]
I didn't quite understand the integration process for thumbfast but I have another thumbnailer script that works pretty fast. If you want I'll add it to the repo.

**Comment by po5** [comment]
I've submitted PRs for https://github.com/cyl0/MordenX and https://github.com/maoiscat/mpv-osc-modern.  
That should be enough to add support for it here, assuming your script is a minor edit of ModernX.

**Comment by 1-minute-to-midnight** [comment]
Idk why but my osc completley disappeared after adding in the changes

**Comment by po5** [comment]
> Idk why but my osc completley disappeared after adding in the changes

That would mean *you* made an error, and the lua is invalid. I've submitted a PR.
