### ISSUE TITLE
Thumbnails not working

### ISSUE THREAD

**Issue by DogancanYr** [1-minute-to-midnight/mpv-modern-x-compact#14]
It could be because I'm using the mpv.net version.

**Comment by 1-minute-to-midnight** [comment]
Are you using the latest the version of the script?

**Comment by DogancanYr** [comment]
Yes.

**Comment by 1-minute-to-midnight** [comment]
Are you using thumbfast?

**Comment by DogancanYr** [comment]
This one didn't work so I switched to that one and thumbfast worked after reading the description of running mpv.net
