### ISSUE TITLE
Feature request : A playback speed toggle 

### ISSUE THREAD

**Issue by houssemko** [1-minute-to-midnight/mpv-modern-x-compact#17]
Can you add a playback speed toggle that can be used with the mouse wheel ?

**Comment by 1-minute-to-midnight** [comment]
Done.

**Comment by houssemko** [comment]
thank you , Suggesting a way to improve it , pressing left click should increase the playback speed by an incremental 1x and pressing right click should switch back to default 1x playback speed

**Comment by 1-minute-to-midnight** [comment]
Ok I have added reset playback speed on right click. For the increments, I prefer 0.5x increase. You can change it a 1.0x increment by going to line 2291 and substitute it with:
```
ne.eventresponder["mbtn_left_up"] =
        function ()
            local current_speed = mp.get_property_number("speed", 1.0)
            if current_speed == 1.0 then
                mp.set_property("speed", 2.0)
            else
                mp.set_property("speed", 1.0)
            end
        end
```

**Comment by houssemko** [comment]
Perfect , thank you .

**Comment by houssemko** [comment]
i think there's a bug with left click to increase the speed , it only works up to 2x and sometimes left click resets the speed .

**Comment by 1-minute-to-midnight** [comment]
It's working exactly as intended hahaha. I'll improve the code a bit for you. Gimme a bit.

**Comment by 1-minute-to-midnight** [comment]
Ok, I have updated the code. Go to line 2293 and you can see the speed values you cycle through, change it to your desired speed values:
`local speeds = {1.0, 2.0, 3.0, 4.0}`
I didn't realize you needed more than 2.0x speed hahaha.
I have also updated the speed increment values to 0.25 in lines 2313 and 2315 for scrolling. You can change them to 1.0 if you wish.

**Comment by houssemko** [comment]
thank you so much
