### ISSUE TITLE
How to hide OSC when paused?

### ISSUE THREAD

**Issue by Duuv1** [1-minute-to-midnight/mpv-modern-x-compact#2]
When I pause the video, the bottom bar appears, how to stopping it from appearing when I pause?

**Comment by 1-minute-to-midnight** [comment]
create osc.conf in script-opts folder and put in the line:
`showonpause=no`

**Comment by perdakovich** [comment]
@1-minute-to-midnight 
[modern] script-opts/osc.conf:1 unknown key 'showonseek', ignoring
[modern] script-opts/osc.conf:2 unknown key 'showonpause', ignoring


~/.config/mpv/script-opts/osc.conf

showonseek=no
showonpause=no
