### ISSUE TITLE
Error from windowcontrols_alignment option

### ISSUE THREAD

**Issue by AndyM48** [1-minute-to-midnight/mpv-modern-x-compact#8]
The script option `windowcontrols_alignment=right` or `windowcontrols_alignment="right"` both produce an error:

```
[modernx] windowcontrols_alignment cannot be "right". Ignoring
[modernx] windowcontrols_alignment cannot be ""right"". Ignoring

```
The default is right, so this will only be a problem if it is set to left :)

**Comment by 1-minute-to-midnight** [comment]
Can't reproduce here. Have you changed anything else in the file? Could you try updating to the latest commit and try again?

**Comment by AndyM48** [comment]
This is now working fine using `windowcontrols_alignment=right`.

`windowcontrols_alignment="right"` will still throw an error, although I think this is normal.

**Comment by 1-minute-to-midnight** [comment]
Then I'll be closing this issue.
