### ISSUE TITLE
Script crashes with Thumbnailer scripts

### ISSUE THREAD

**Issue by AndyM48** [1-minute-to-midnight/mpv-modern-x-compact#9]
The error is:

```
[modernx] stack traceback:
[modernx] 	/home/andrew/.config/pp_mpv/scripts/modernx.lua:413: in function 'display_tn_osc'
[modernx] 	/home/andrew/.config/pp_mpv/scripts/modernx.lua:1282: in function 'render_elements'
[modernx] 	/home/andrew/.config/pp_mpv/scripts/modernx.lua:2558: in function 'render'
[modernx] 	/home/andrew/.config/pp_mpv/scripts/modernx.lua:2727: in function 'cb'
[modernx] 	mp.defaults:361: in function 'process_timers'
[modernx] 	mp.defaults:530: in function 'dispatch_events'
[modernx] 	mp.defaults:503: in function <mp.defaults:502>
[modernx] 	[C]: at 0x560437fbf780
[modernx] 	[C]: at 0x560437fbff30
[modernx] Lua error: /home/andrew/.config/pp_mpv/scripts/modernx.lua:330: attempt to call a nil value
```

This does not seem to  happen with Thumbfast :)

This may refer: https://github.com/1-minute-to-midnight/mpv-modern-x-compact/issues/1#issuecomment-1296002108

**Comment by 1-minute-to-midnight** [comment]
It seems to be working for me 😅. There have been a few updates. Could you try again after getting the latest commits and let me know?

**Comment by AndyM48** [comment]
This is the same error as #8 viz. setting `layout="modernx"` in the osc.conf creates the error. setting `layout=modernx` works.

**Comment by po5** [comment]
User error. You've set `layout` to an unsupported value. Only these are supported:
https://github.com/1-minute-to-midnight/mpv-modern-x-compact/blob/232c70780ef4a9ca20b3def549b2dc5c3d4715d8/modernx.lua#L256-L268

**Comment by AndyM48** [comment]
It was simple when I finally understood it. Do not use quotes after = in a .conf file
